// Generated by android-multi-flavor-google skill v1.3.0
// Template: {{appPrefix}}AdjustAttributionImpl.kt (src/{{flavorName}}/)
// ⚠️ Placeholders ({{...}}) must be substituted before use
// ⚠️ 仅在选择 Adjust 归因方案时生成此文件
// ⚠️ 本文件放到 src/{{flavorName}}/java/{{packagePath}}/google/

package {{packageName}}.google

import android.app.Application
import {{packageName}}.BuildConfig
import com.adjust.sdk.Adjust
import com.adjust.sdk.AdjustConfig

/**
 * Adjust 归因实现(默认方案)。
 * 初始化 Adjust SDK → 获取 GAID + ADID → 回调 onGoogleAdIdReady / onAttributionReady。
 */
internal class {{appPrefix}}AdjustAttributionImpl : {{appPrefix}}AttributionService {

    override fun init(
        application: Application,
        onGoogleAdIdReady: (String) -> Unit,
        onAttributionReady: (String, String?) -> Unit,
    ) {
        val config = AdjustConfig(
            application,
            "{{adjustToken}}",
            AdjustConfig.ENVIRONMENT_PRODUCTION
        )
        Adjust.addGlobalCallbackParameter(
            "custom_app_version", BuildConfig.VERSION_CODE.toString()
        )

        Adjust.initSdk(config)

        // 获取 Adjust 设备 ID（同步，initSdk 后立即可用，32 位 hex）
        val adid = Adjust.getAdid()

        // 获取 Google Advertising ID,回调给上层写 DataStore
        // 如果返回 null,检查是否缺少 play-services-ads-identifier 依赖(见 references/traps.md 陷阱 8)
        Adjust.getGoogleAdId(application) { adId ->
            adId?.let { onGoogleAdIdReady(it) }
            // Adjust 不需要归因数据回调,attributionData 传 null
            onAttributionReady(adid ?: "", null)
        }
    }
}
