// Generated by android-multi-flavor-google skill v1.3.0
// Template: {{appClass}}.kt (Application integration)
// ⚠️ Placeholders ({{...}}) must be substituted before use
// ⚠️ 将本文件内容合并到项目现有的 Application 类中

package {{packageName}}

import android.app.Activity
import android.app.Application
import android.content.Context
import android.os.Bundle
import {{packageName}}.base.attributionDataKey
import {{packageName}}.base.attributionDeviceIdKey
import {{packageName}}.base.fcmTokenKey
import {{packageName}}.base.googleAdIdKey
import {{packageName}}.base.putValue
import {{packageName}}.google.{{appPrefix}}GoogleServices
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.SupervisorJob
import kotlinx.coroutines.launch
import java.lang.ref.WeakReference

class {{appClass}} : Application() {
    private val appScope = CoroutineScope(SupervisorJob() + Dispatchers.IO)

    override fun onCreate() {
        super.onCreate()
        context = this

        // Google 服务初始化:devTest/preProduct 是 No-Op,{{flavorName}} 才连接真实 SDK
        {{appPrefix}}GoogleServices.instance.init(
            application = this,
            onGoogleAdIdReady = { adId ->
                appScope.launch { googleAdIdKey.putValue(adId) }
            },
            onFcmTokenReady = { token ->
                appScope.launch { fcmTokenKey.putValue(token) }
            },
            onAttributionReady = { attributionDeviceId, attributionData ->
                appScope.launch {
                    attributionDeviceIdKey.putValue(attributionDeviceId)
                    attributionData?.let { attributionDataKey.putValue(it) }
                }
            },
        )

        // BEGIN lifecycle.manual
        registerActivityLifecycleCallbacks(activityLifecycleCallbacks)
        // END lifecycle.manual
    }

    // 当前可见 Activity 弱引用(避免内存泄漏)
    var currentActivity: WeakReference<Activity>? = null
        private set

    // BEGIN lifecycle.manual
    private val activityLifecycleCallbacks = object : ActivityLifecycleCallbacks {
        override fun onActivityCreated(activity: Activity, savedInstanceState: Bundle?) {
            currentActivity = WeakReference(activity)
        }
        override fun onActivityStarted(activity: Activity) {}
        override fun onActivityResumed(activity: Activity) {
            currentActivity = WeakReference(activity)
            {{appPrefix}}GoogleServices.instance.onActivityResumed(activity)
        }
        override fun onActivityPaused(activity: Activity) {
            {{appPrefix}}GoogleServices.instance.onActivityPaused(activity)
        }
        override fun onActivityStopped(activity: Activity) {}
        override fun onActivitySaveInstanceState(activity: Activity, outState: Bundle) {}
        override fun onActivityDestroyed(activity: Activity) {}
    }
    // END lifecycle.manual

    companion object {
        lateinit var context: {{appClass}} private set
        // Prefer appContext for most use cases; context only when the concrete Application subclass is needed
        val appContext: Context get() = context.applicationContext
    }
}
