// Generated by android-multi-flavor-google skill v1.3.0
// Template: {{appPrefix}}AppsFlyerAttributionImpl.kt (src/{{flavorName}}/)
// ⚠️ Placeholders ({{...}}) must be substituted before use
// ⚠️ 仅在选择 AppsFlyer 归因方案时生成此文件
// ⚠️ 本文件放到 src/{{flavorName}}/java/{{packagePath}}/google/

package {{packageName}}.google

import android.app.Application
import android.util.Log
import {{packageName}}.BuildConfig
import com.appsflyer.AppsFlyerConversionListener
import com.appsflyer.AppsFlyerLib
import com.google.android.gms.ads.identifier.AdvertisingIdClient
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.SupervisorJob
import kotlinx.coroutines.launch
import org.json.JSONObject

/**
 * AppsFlyer 归因实现(备选方案)。
 * 初始化 AppsFlyer SDK → 手动获取 GAID → ConversionDataListener 回调归因数据。
 */
internal class {{appPrefix}}AppsFlyerAttributionImpl : {{appPrefix}}AttributionService {
    private val scope = CoroutineScope(SupervisorJob() + Dispatchers.IO)

    companion object {
        private const val TAG = "AppsFlyerAttribution"
    }

    override fun init(
        application: Application,
        onGoogleAdIdReady: (String) -> Unit,
        onAttributionReady: (String, String?) -> Unit,
    ) {
        // 1. 手动获取 Google Advertising ID(AppsFlyer 不封装此逻辑)
        scope.launch {
            try {
                val adInfo = AdvertisingIdClient.getAdvertisingIdInfo(application)
                onGoogleAdIdReady(adInfo.id)
            } catch (e: Exception) {
                Log.w(TAG, "Failed to get GAID: ${e.message}")
            }
        }

        // 2. 设置自定义归因参数
        AppsFlyerLib.getInstance().setAdditionalData(
            mapOf(
                "custom_app_version" to BuildConfig.VERSION_CODE.toString()
            )
        )

        // 3. 初始化 SDK 并注册归因回调
        AppsFlyerLib.getInstance().init(
            "{{appsFlyerDevKey}}",
            object : AppsFlyerConversionListener {
                override fun onConversionDataSuccess(data: MutableMap<String, Any>) {
                    val result = data.mapValues { it.value.toString() }.toMutableMap()
                    result["attribution_sdk"] = "appsflyer"
                    val json = JSONObject(result).toString()
                    val deviceId = AppsFlyerLib.getInstance().getAppsFlyerUID(application) ?: ""
                    onAttributionReady(deviceId, json)
                }
                override fun onConversionDataFail(error: String) {
                    Log.w(TAG, "onConversionDataFail: $error")
                    onAttributionReady("", """{"attribution_sdk":"appsflyer","error":"$error"}""")
                }
                override fun onAppOpenAttribution(data: MutableMap<String, String>?) {
                    data?.let { Log.i(TAG, "onAppOpenAttribution: $it") }
                }
                override fun onAttributionFailure(error: String) {
                    Log.w(TAG, "onAttributionFailure: $error")
                }
            },
            application
        )

        // 4. 启动 SDK 归因(start() 必须在主线程调用)
        AppsFlyerLib.getInstance().start(application)
    }
}
