// Generated by android-multi-flavor-google skill v1.3.0
// Template: {{appPrefix}}AttributionService.kt
// ⚠️ Placeholders ({{...}}) must be substituted before use

package {{packageName}}.google

import android.app.Application

/**
 * 归因服务抽象(运行在 {{flavorName}} flavor)。
 * [init] 初始化归因 SDK,归因数据通过回调传给上层。
 *
 * 生命周期方法由 [{{appPrefix}}GoogleService] 统一声明,
 * [{{appPrefix}}GoogleServiceImpl] 根据归因方案直接调用对应 SDK,
 * 本接口不声明生命周期方法以避免与 GoogleService 重复。
 */
interface {{appPrefix}}AttributionService {
    /**
     * 初始化归因 SDK。
     *
     * @param onGoogleAdIdReady GAID 获取成功回调(Adjust 内部获取 / AppsFlyer 手动获取)
     * @param onAttributionReady 首次归因结果回调
     *        attributionDeviceId: 归因工具设备 ID
     *          - Adjust: Adjust.getAdid() — 32 位 hex,服务端 S2S / 反作弊 / 重装识别
     *          - AppsFlyer: AppsFlyerLib.getAppsFlyerUID() — AppsFlyer 自有设备 ID
     *        attributionData: 归因数据 JSON 字符串,可空
     *          - Adjust: null(不需要归因数据)
     *          - AppsFlyer: {"af_status":"Organic","media_source":"direct"...}
     *          - 非归因渠道(No-Op)不调用此回调
     */
    fun init(
        application: Application,
        onGoogleAdIdReady: (String) -> Unit,
        onAttributionReady: (attributionDeviceId: String, attributionData: String?) -> Unit,
    )
}
