// Generated by android-multi-flavor-google skill v1.3.0
// Template: build.gradle.kts (app module)
// ⚠️ Placeholders ({{...}}) must be substituted before use
// ⚠️ 项目现有 plugins/namespace/compileSdk/defaultConfig 请按项目实际情况保留

// 从 gradle.properties 安全读取签名凭据（凭据不入 git）
fun Project.secret(key: String): String =
    providers.gradleProperty(key).orNull
        ?: error("Missing gradle property: $key")

plugins {
    alias(libs.plugins.android.application)
    // 项目现有 plugins — 请按实际项目保留/删减
    alias(libs.plugins.kotlin.compose)
    alias(libs.plugins.kotlin.serialization)
    // google-services / firebase-crashlytics plugin 由下方按 task name 条件 apply
}

android {
    namespace = "{{namespace}}"
    // ... compileSdk / defaultConfig 按项目原状

    /**
     * ================== Signing ==================
     * 双签名方案：测试渠道用 testRelease，生产渠道用独立签名
     * 凭据通过 secret() 从 gradle.properties 读取，不硬编码
     */
    signingConfigs {
        // 测试、验证使用的签名信息（devTest / preProduct）
        create("testRelease") {
            storeFile = file(secret("TEST_STORE_FILE"))
            storePassword = secret("TEST_STORE_PASSWORD")
            keyAlias = secret("TEST_KEY_ALIAS")
            keyPassword = secret("TEST_KEY_PASSWORD")
        }
        // 正式上架的签名文件配置（{{flavorName}}）
        create("{{flavorName}}Release") {
            storeFile = file(secret("GOOGLE_STORE_FILE"))
            storePassword = secret("GOOGLE_STORE_PASSWORD")
            keyAlias = secret("GOOGLE_KEY_ALIAS")
            keyPassword = secret("GOOGLE_KEY_PASSWORD")
        }
    }

    // 唯一 flavor 维度:env
    // ⚠️ 如果项目已有 flavorDimensions，请手动合并而非覆盖
    flavorDimensions = listOf("env")

    productFlavors {
        create("devTest") {
            dimension = "env"
            buildConfigField("String", "BASE_URL", "\"{{devBaseUrl}}\"")
            buildConfigField("String", "WEB_URL", "\"{{devWebUrl}}\"")
            buildConfigField("String", "FLAVOR_ENV", "\"devTest\"")
        }
        create("preProduct") {
            dimension = "env"
            // 生产域名 + 不含 Google,用于上线前真域名走查
            buildConfigField("String", "BASE_URL", "\"{{prodBaseUrl}}\"")
            buildConfigField("String", "WEB_URL", "\"{{prodWebUrl}}\"")
            buildConfigField("String", "FLAVOR_ENV", "\"preProduct\"")
        }
        create("{{flavorName}}") {
            dimension = "env"
            // 生产域名 + Firebase/归因/FCM/谷歌好评(完整上线包)
            buildConfigField("String", "BASE_URL", "\"{{prodBaseUrl}}\"")
            buildConfigField("String", "WEB_URL", "\"{{prodWebUrl}}\"")
            buildConfigField("String", "FLAVOR_ENV", "\"{{flavorName}}\"")
        }
    }

    buildTypes {
        debug {
            // devTestDebug 用测试签名但不混淆,保留断点调试与符号信息
            isMinifyEnabled = false
            isShrinkResources = false
            buildConfigField("Boolean", "ENABLE_LOG", "true")
        }
        release {
            isMinifyEnabled = true
            isShrinkResources = true
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
            buildConfigField("Boolean", "ENABLE_LOG", "false")
        }
    }

    buildFeatures {
        compose = true
        buildConfig = true
    }

    // sourceSet 隔离:devTest/preProduct 共享 src/{{noFlavorName}}/;{{flavorName}} 用 src/{{flavorName}}/
    // ⚠️ 关键陷阱:AGP 9 + Kotlin 2.x 把 .kt 源剥到独立的 kotlin sourceDirectorySet,
    // 必须同时在 kotlin.srcDirs 列出 {{noFlavorName}}/java 路径(否则 Kotlin 编译器看不到)
    // srcDirs(varargs) 在 AGP 9 已 deprecate,等官方稳定的替代 API(directories mutable set)成熟再迁
    @Suppress("DEPRECATION")
    sourceSets {
        getByName("devTest") {
            java.srcDirs("src/devTest/java", "src/{{noFlavorName}}/java")
            kotlin.srcDirs("src/devTest/java", "src/{{noFlavorName}}/java")
            res.srcDirs("src/devTest/res", "src/{{noFlavorName}}/res")
        }
        getByName("preProduct") {
            java.srcDirs("src/preProduct/java", "src/{{noFlavorName}}/java")
            kotlin.srcDirs("src/preProduct/java", "src/{{noFlavorName}}/java")
            res.srcDirs("src/preProduct/res", "src/{{noFlavorName}}/res")
        }
        getByName("{{flavorName}}") {
            // {{flavorName}} flavor 默认就会扫 src/{{flavorName}}/java 与 src/{{flavorName}}/res,只显式声明 Manifest 路径
            manifest.srcFile("src/{{flavorName}}/AndroidManifest.xml")
        }
    }
}

// 按渠道分发签名 + 关闭无意义的 variant
// AGP 9 推荐用 androidComponents.beforeVariants,而非过时的 variantFilter
androidComponents {
    // 按渠道分发签名：生产用正式签名，其余用测试签名
    beforeVariants { variant ->
        val flavor = variant.productFlavors.firstOrNull { it.first == "env" }?.second
        variant.signingConfig = when (flavor) {
            "{{flavorName}}" -> signingConfigs.getByName("{{flavorName}}Release")
            else             -> signingConfigs.getByName("testRelease")
        }
    }

    // 关闭无意义的 variant:preProductDebug / {{flavorName}}Debug
    beforeVariants(selector().withBuildType("debug")) { variant ->
        val flavor = variant.productFlavors.firstOrNull { it.first == "env" }?.second
        if (flavor == "preProduct" || flavor == "{{flavorName}}") {
            variant.enable = false
        }
    }
}

// Google plugin 按 task 名条件 apply
//  - CLI 跑 `./gradlew :app:assemble{{FlavorName}}Release` 时 taskNames 含 "{{FlavorName}}",apply 生效
//  - IDE 显式打 {{flavorName}} 包(Build APK / Generate Signed Bundle / Run)task 一定含 "{{FlavorName}}",apply 生效
//  - IDE Project Sync / 跑 devTest/preProduct task 时不含 "{{FlavorName}}",plugin 不 apply
//  - `./gradlew build` 或 `./gradlew assemble` 不指定 variant 时 taskNames 不含 "{{FlavorName}}",
//    此时用 -PenableGooglePlugin 兜底
//
//  注意:BuildConfig 切换与本判断无关 —— AGP 为每个 variant 独立生成 BuildConfig.java,
//  只要 variant 选对,BASE_URL/WEB_URL/FLAVOR_ENV/ENABLE_LOG 就一定切到对应 flavor
val isGoogleBuild = gradle.startParameter.taskNames.any { taskName ->
    taskName.contains("{{FlavorName}}", ignoreCase = true)
} || project.hasProperty("enableGooglePlugin")

// 控制台 print:每次 gradle 跑都能在日志开头看到 plugin apply 状态,便于排查
println("[App] taskNames=${gradle.startParameter.taskNames}, isGoogleBuild=$isGoogleBuild")
if (isGoogleBuild) {
    apply(plugin = libs.plugins.gms.google.services.get().pluginId)
    apply(plugin = libs.plugins.firebase.crashlytics.get().pluginId)
}

dependencies {
    // ... 项目原有依赖(implementation 等)

    // Google 依赖:只在 {{flavorName}} flavor 打入 APK(devTest/preProduct classpath 完全无 Google 字节码)
    // variant-aware configuration 名必须用字符串字面量("{{flavorName}}" + "Implementation" 拼接)
    "{{flavorName}}Implementation"(platform(libs.firebase.bom))
    "{{flavorName}}Implementation"(libs.firebase.analytics)
    "{{flavorName}}Implementation"(libs.firebase.crashlytics)
    "{{flavorName}}Implementation"(libs.firebase.crashlytics.ndk)        // C/C++ 层崩溃捕获
    "{{flavorName}}Implementation"(libs.firebase.messaging)
    "{{flavorName}}Implementation"(libs.play.review.ktx)

    // BEGIN attribution.adjust
    "{{flavorName}}Implementation"(libs.adjust.sdk)
    "{{flavorName}}Implementation"(libs.adjust.webbridge)                // WebView 内归因事件桥接
    // END attribution.adjust
    // BEGIN attribution.appsflyer
    "{{flavorName}}Implementation"(libs.appsflyer.sdk)
    // END attribution.appsflyer

    // [共用] Install Referrer + Advertising ID,两个归因方案都需要
    "{{flavorName}}Implementation"(libs.installreferrer)
    "{{flavorName}}Implementation"(libs.play.services.ads.identifier)
}
