// Generated by android-multi-flavor-google skill v1.3.0
// Template: DataStore.kt (追加字段)
// ⚠️ Placeholders ({{...}}) must be substituted before use
// ⚠️ 将以下字段追加到项目现有的 DataStore.kt 文件中
// ⚠️ 需要 import androidx.datastore.preferences.core.stringPreferencesKey

// FCM 推送 token(由 FCM Service.onNewToken 写入,登录时上传给服务端)
val fcmTokenKey = stringPreferencesKey("FcmToken")

// Google Advertising ID(由归因 SDK 回调写入,网络层 header 用)
val googleAdIdKey = stringPreferencesKey("GoogleAdId")

// 归因数据 JSON(由归因 SDK 回调写入,包含 googleAdId / attribution_sdk / media_source / campaign 等)
// ⚠️ putValue 扩展函数需要 DataStore<Preferences>.edit { it[stringPreferencesKey] = value }
val attributionDataKey = stringPreferencesKey("AttributionData")

// 归因工具设备 ID(由归因 SDK 回调写入)
// - Adjust: Adjust.getAdid() — 32 位 hex
// - AppsFlyer: AppsFlyerLib.getAppsFlyerUID()
val attributionDeviceIdKey = stringPreferencesKey("AttributionDeviceId")
