// Generated by android-multi-flavor-google skill v1.3.0
// Template: {{appPrefix}}GoogleServiceImpl.kt (real — src/{{flavorName}}/)
// ⚠️ Placeholders ({{...}}) must be substituted before use
// ⚠️ 本文件放到 src/{{flavorName}}/java/{{packagePath}}/google/

package {{packageName}}.google

import android.app.Activity
import android.app.Application

/**
 * {{flavorName}} flavor 使用的真实实现。
 *
 * 所有 SDK 调用直接写入可运行代码,不再注释。
 * 归因逻辑委托给 [{{appPrefix}}AttributionService] 实现,通过构造函数注入。
 * 本类与 src/{{noFlavorName}}/.../{{appPrefix}}GoogleServiceImpl 同名同包,编译期由 AGP 二选一。
 */
internal class {{appPrefix}}GoogleServiceImpl : {{appPrefix}}GoogleService {

    // 归因服务实现(根据归因方案选择,AI 在生成时裁剪以下条件块)
    private val attribution: {{appPrefix}}AttributionService =
    // BEGIN attribution.adjust
        {{appPrefix}}AdjustAttributionImpl()
    // END attribution.adjust
    // BEGIN attribution.appsflyer
        {{appPrefix}}AppsFlyerAttributionImpl()
    // END attribution.appsflyer

    override fun init(
        application: Application,
        onGoogleAdIdReady: (String) -> Unit,
        onFcmTokenReady: (String) -> Unit,
        onAttributionReady: (String, String?) -> Unit,  // (attributionDeviceId, attributionData?)
    ) {
        // ─── 归因初始化(委托给 AttributionService,回调直接透传到 Application 层) ──
        attribution.init(
            application,
            onGoogleAdIdReady = onGoogleAdIdReady,
            onAttributionReady = onAttributionReady,
        )

        // ─── Firebase 初始化(同时启用 Crashlytics 自动崩溃收集) ──────────
        com.google.firebase.FirebaseApp.initializeApp(application)

        // ─── FCM token 首次拉取 ────────────────────────────────────────
        com.google.firebase.messaging.FirebaseMessaging.getInstance().token
            .addOnSuccessListener { token -> token?.let(onFcmTokenReady) }
    }

    // BEGIN lifecycle.manual
    override fun onActivityResumed(activity: Activity) {
        // BEGIN attribution.adjust
        // Adjust 5.x 内部自动注册 ActivityLifecycleCallbacks,无需手动调用
        // END attribution.adjust
        // BEGIN attribution.appsflyer
        com.appsflyer.AppsFlyerLib.getInstance().start(activity)
        // END attribution.appsflyer
    }

    override fun onActivityPaused(activity: Activity) {
        // BEGIN attribution.adjust
        // Adjust 5.x 内部自动注册 ActivityLifecycleCallbacks,无需手动调用
        // END attribution.adjust
        // BEGIN attribution.appsflyer
        com.appsflyer.AppsFlyerLib.getInstance().stop()
        // END attribution.appsflyer
    }
    // END lifecycle.manual

    override fun requestReview(activity: Activity, onComplete: (Boolean) -> Unit) {
        val manager = com.google.android.play.core.review.ReviewManagerFactory.create(activity)
        manager.requestReviewFlow().addOnCompleteListener { req ->
            if (req.isSuccessful) {
                manager.launchReviewFlow(activity, req.result).addOnCompleteListener { onComplete(true) }
            } else onComplete(false)
        }
    }
}
