// Generated by android-multi-flavor-google skill v1.3.0
// Template: {{appPrefix}}GoogleServices.kt
// ⚠️ Placeholders ({{...}}) must be substituted before use

package {{packageName}}.google

/**
 * Google 服务入口。
 * [{{appPrefix}}GoogleServiceImpl] 由 sourceSet 二选一提供({{noFlavorName}}/{{flavorName}}),
 * 编译期由 AGP 二选一,业务侧统一通过 [instance] 调用。
 *
 * 归因逻辑封装在 [{{appPrefix}}GoogleServiceImpl] 内部,
 * 通过 [{{appPrefix}}AttributionService] 委托实现,
 * 归因数据通过 [{{appPrefix}}GoogleService.init] 回调到 Application 层写入 DataStore。
 */
object {{appPrefix}}GoogleServices {
    val instance: {{appPrefix}}GoogleService = {{appPrefix}}GoogleServiceImpl()
}
