// Generated by android-multi-flavor-google skill v1.3.0
// Template: {{appPrefix}}GoogleService.kt
// ⚠️ Placeholders ({{...}}) must be substituted before use

package {{packageName}}.google

import android.app.Activity
import android.app.Application

/**
 * Google 应用层服务抽象。
 * 由 Application.onCreate 调用,真实实现在 {{flavorName}} flavor 完成归因 + Firebase 初始化。
 */
interface {{appPrefix}}GoogleService {
    /**
     * Application.onCreate 调用一次。真实实现内部完成:
     *  1. 归因 SDK 初始化(Adjust 或 AppsFlyer)
     *  2. 获取 Google Advertising ID → [onGoogleAdIdReady]
     *  3. FirebaseApp.initializeApp(同时启用 Crashlytics 自动崩溃收集)
     *  4. 首次拉取 FCM token → [onFcmTokenReady]
     *  5. 归因数据就绪 → [onAttributionReady]
     *  (后续 FCM Service.onNewToken 直接写 DataStore,不再回调)
     *
     * @param onGoogleAdIdReady Google Advertising ID 获取成功回调
     * @param onFcmTokenReady FCM Push Token 首次获取成功回调
     * @param onAttributionReady 归因数据就绪回调
     *        attributionDeviceId: 归因工具设备 ID
     *          - Adjust: Adjust.getAdid() — 32 位 hex,服务端 S2S / 反作弊 / 重装识别
     *          - AppsFlyer: AppsFlyerLib.getAppsFlyerUID() — AppsFlyer 自有设备 ID
     *        attributionData: 归因数据 JSON 字符串,可空
     *          - Adjust: null(不需要归因数据)
     *          - AppsFlyer: 归因字段 JSON
     *          - 非归因渠道(No-Op)不调用此回调
     */
    fun init(
        application: Application,
        onGoogleAdIdReady: (String) -> Unit,
        onFcmTokenReady: (String) -> Unit,
        onAttributionReady: (attributionDeviceId: String, attributionData: String?) -> Unit,
    )

    // BEGIN lifecycle.manual
    /** Activity onResume 转发,真实实现调归因 SDK 的生命周期方法 */
    fun onActivityResumed(activity: Activity)
    /** Activity onPause 转发 */
    fun onActivityPaused(activity: Activity)
    // END lifecycle.manual

    /**
     * Google Play 应用内好评。
     * devTest/preProduct 直接 onComplete(false),{{flavorName}} flavor 走 ReviewManagerFactory。
     * @param onComplete success=true 表示弹窗已展示(无论是否打星);
     *                   false 表示因 Play Store 限流/非 Play 渠道安装等原因未展示。
     */
    fun requestReview(activity: Activity, onComplete: (success: Boolean) -> Unit)
}
