// Generated by android-multi-flavor-google skill v1.3.0
// Template: {{appPrefix}}GoogleServiceImpl.kt (noop — src/{{noFlavorName}}/)
// ⚠️ Placeholders ({{...}}) must be substituted before use
// ⚠️ 本文件放到 src/{{noFlavorName}}/java/{{packagePath}}/google/

package {{packageName}}.google

import android.app.Activity
import android.app.Application
{{loggerImport}}

/**
 * devTest / preProduct flavor 使用的 No-Op 实现。
 * 全部空实现,APK 内不会出现 com.google.* / com.adjust.* / com.appsflyer.* 任何符号。
 *
 * 关键:本类与 src/{{flavorName}}/.../{{appPrefix}}GoogleServiceImpl 同名同包,编译期由 AGP 二选一。
 */
internal class {{appPrefix}}GoogleServiceImpl : {{appPrefix}}GoogleService {

    private val TAG = "{{appPrefix}}Google"

    override fun init(
        application: Application,
        onGoogleAdIdReady: (String) -> Unit,
        onFcmTokenReady: (String) -> Unit,
        onAttributionReady: (String, String?) -> Unit,  // No-Op 不会调用此回调
    ) {
        Log.d(TAG, "[noop] init (devTest/preProduct flavor)")
    }

    // BEGIN lifecycle.manual
    override fun onActivityResumed(activity: Activity) { /* no-op */ }
    override fun onActivityPaused(activity: Activity) { /* no-op */ }
    // END lifecycle.manual

    override fun requestReview(activity: Activity, onComplete: (Boolean) -> Unit) {
        Log.d(TAG, "[noop] requestReview")
        onComplete(false)
    }
}
