# Generated by android-multi-flavor-google skill v1.3.0
# Template: proguard-rules.pro
# ⚠️ Placeholders ({{...}}) must be substituted before use
# ⚠️ Append to existing app/proguard-rules.pro, do not replace

# ══════════════════════════════════════════════════════════
# Firebase SDK (always needed for {{flavorName}} flavor)
# ══════════════════════════════════════════════════════════
-keep class com.google.firebase.** { *; }
-dontwarn com.google.firebase.**

# ══════════════════════════════════════════════════════════
# Google Play Services — Advertising ID (shared by both attribution schemes)
# ══════════════════════════════════════════════════════════
-keep class com.google.android.gms.ads.identifier.** { *; }

# BEGIN attribution.adjust
# ══════════════════════════════════════════════════════════
# Adjust SDK
# ══════════════════════════════════════════════════════════
-keep class com.adjust.sdk.** { *; }
# END attribution.adjust

# BEGIN attribution.appsflyer
# ══════════════════════════════════════════════════════════
# AppsFlyer SDK
# ══════════════════════════════════════════════════════════
-keep class com.appsflyer.** { *; }
-dontwarn com.appsflyer.**
# END attribution.appsflyer
