// Generated by android-multi-flavor-google skill v1.3.0
// Template: {{appPrefix}}PushService.kt (src/{{flavorName}}/)
// ⚠️ Placeholders ({{...}}) must be substituted before use
// ⚠️ 本文件放到 src/{{flavorName}}/java/{{packagePath}}/google/
// ⚠️ 如果项目是多模块结构,R 类可能位于不同包名下,请根据实际调整 import

package {{packageName}}.google

import android.app.NotificationChannel
import android.app.NotificationManager
import android.app.PendingIntent
import android.content.Context
import android.content.Intent
import android.media.RingtoneManager
import android.os.Build
import android.util.Log
import androidx.core.app.NotificationCompat
import {{packageName}}.R
import {{packageName}}.base.fcmTokenKey
import {{packageName}}.base.putValue
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.SupervisorJob
import kotlinx.coroutines.cancel
import kotlinx.coroutines.launch
import java.util.concurrent.atomic.AtomicLong

/**
 * FCM 推送 Service。仅在 {{flavorName}} flavor 编译进 APK,由 src/{{flavorName}}/AndroidManifest.xml 静态注册。
 *
 * 继承 [com.google.firebase.messaging.FirebaseMessagingService],直接响应 FCM MESSAGING_EVENT。
 * Token 处理:onNewToken 直接写 DataStore.fcmTokenKey,业务侧从 DataStore 订阅。
 * 通知图标:setSmallIcon(R.mipmap.ic_launcher),后续设计交付专用 notification icon 后替换。
 */
class {{appPrefix}}PushService : com.google.firebase.messaging.FirebaseMessagingService() {

    private val scope = CoroutineScope(SupervisorJob() + Dispatchers.IO)
    private val notificationIdCounter = AtomicLong(System.currentTimeMillis())

    companion object {
        private const val TAG = "{{appPrefix}}Push"
        private const val CHANNEL_ID = "{{appPrefix}}"
    }

    override fun onCreate() {
        super.onCreate()
        // 一次性创建 NotificationChannel,避免每次通知时重复创建
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            val channel = NotificationChannel(
                CHANNEL_ID,
                CHANNEL_ID,
                NotificationManager.IMPORTANCE_DEFAULT
            )
            val manager = getSystemService(Context.NOTIFICATION_SERVICE) as NotificationManager
            manager.createNotificationChannel(channel)
        }
    }

    override fun onMessageReceived(message: com.google.firebase.messaging.RemoteMessage) {
        message.notification?.let {
            runCatching { showNotification(it.title, it.body) }
                .onFailure { e -> Log.e(TAG, "showNotification failed", e) }
        }
    }

    override fun onNewToken(token: String) {
        super.onNewToken(token)
        scope.launch { fcmTokenKey.putValue(token) }
    }

    override fun onDestroy() {
        super.onDestroy()
        scope.cancel()
    }

    private fun showNotification(title: String?, body: String?) {
        val intent = Intent().apply { addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP) }
        val pendingFlag = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
            PendingIntent.FLAG_IMMUTABLE or PendingIntent.FLAG_ONE_SHOT
        } else {
            PendingIntent.FLAG_ONE_SHOT
        }
        // 使用唯一 requestCode 避免多条通知的 PendingIntent 互相覆盖
        val requestCode = (notificationIdCounter.incrementAndGet() % Int.MAX_VALUE).toInt()
        val pendingIntent = PendingIntent.getActivity(this, requestCode, intent, pendingFlag)
        val soundUri = RingtoneManager.getDefaultUri(RingtoneManager.TYPE_NOTIFICATION)
        val notification = NotificationCompat.Builder(this, CHANNEL_ID)
            .setSmallIcon(R.mipmap.ic_launcher)
            .setContentTitle(title ?: "")
            .setContentText(body ?: "")
            .setStyle(NotificationCompat.BigTextStyle().bigText(body ?: ""))
            .setAutoCancel(true)
            .setSound(soundUri)
            .setContentIntent(pendingIntent)
            .build()
        val manager = getSystemService(Context.NOTIFICATION_SERVICE) as NotificationManager
        // 使用唯一 notificationId 支持多条通知同时显示
        val notificationId = (notificationIdCounter.incrementAndGet() % Int.MAX_VALUE).toInt()
        manager.notify(notificationId, notification)
    }
}
